### ISSUE TITLE
Interaction validations are optional

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#122]
From "Interaction Activities" in xAPI-Data:

```
An LRS, upon consuming a valid interactionType, MAY validate the remaining properties as specified for Interaction Activities and MAY return 400 Bad Request if the remaining properties are not valid for the Interaction Activity.
```
This is a more specific requirement than the formatting requirements in section 2.2 which indicate that an LRS MUST reject statements where .... https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#lrs-requirements

Since the `MAY` requirement is more specific (limited to interaction activities), and because is has no meaning if it doesn't take precedence, it should be read as taking precedence over the general `MUST` reject statements in 2.2

Therefore, tests relating to interactiontype (eg: "when interactionType is _something_ then _something") and relying on Data#2.2.x as rationale should either only be run when requested, or should be noted as some sort of warning only, not failures.

**Comment by ljwolford** [comment]
I think these tests are only validating the value of `interactionType`, so they should be OK since the requirement above the `MAY` says:

`Interaction Activities MUST have a valid interactionType.`

If these were testing `correctResponsPattern` or any of the interaction components then I'd agree, there shouldn't be any of those in the tests.

**Comment by bscSCORM** [comment]
@ljwolford you're right, not sure what I thought I was seeing. Thanks!
