### ISSUE TITLE
Activity Definition is empty and the platform expects 200

### ISSUE THREAD

**Issue by castasamu** [adlnet/lrs-conformance-test-suite#130]
The test:
> "An Activity Definition contains at least one of the following properties: name, description, type, moreInfo, interactionType, or extensions"

> "statement activity \"definition\" missing all properties"

> "statement substatement activity \"definition\" missing all properties"

`{ ... "definition":{}}`

> "Error: Expected response status code to be 200 got 400

The state code of the response must be 400

**Comment by cr8onski** [comment]
In [Data 2.4.4.1 Table 2](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2.4.4.1.s2) every property that makes up an activity definition is either "recommended" or "optional".  And in [Data 2.2](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2.2.s2.b1) the requirement about using empty objects is SHOULD NOT.

please see:  https://github.com/adlnet/grail-issue-tracker/issues/27

I also see that the title of the test is misleading and will make a change so that it better reflects the spec.

**Comment by castasamu** [comment]
Thanks a lot!!!
