### ISSUE TITLE
Behavior difference in Statement/Activities routes

### ISSUE THREAD

**Issue by TylerDixon** [adlnet/lrs-conformance-test-suite#152]
In a test [here](https://github.com/adlnet/lrs-conformance-test-suite/blob/acaea76881215b683eb96fd5541cf572e8f876ae/test/v1_0_3/H.Communication1.3-AlternateRequestSyntax.js#L71-L99). A request is made to store a statement, then get information about the activity stored with that statement via the [activities resource](https://github.com/adlnet/xAPI-Spec/blob/5ef45de33cf7cb189d0e455e7829794a20418a42/xAPI-Communication.md#25-activities-resource). 

Looking at the documentation for the activities resource, there is no specification that activity details from posted statements should be available through the route. 

I could be missing the link between these two resources in the documentation, or it could be missing itself. Also, option 3, I could be completely misinterpreting the test. Could anyone shed some light on this for me?

**Comment by garemoko** [comment]
[Here](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#25-activities-resource) states that the LRS is supposed to return it's canonical definition for the activity. 

[Here](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#lrs-requirements-1) and [here](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#32-hosted-metadata) describe two possibly (non-exhaustive) ways in which an LRS might update its canonical definition. 

The LRS has a lot of flexibility in determining whether or not to update it's canonical definition and the requirement to update the canonical definition on new statements is a SHOULD (because the LRS might have another more trusted source for the definition). In the test suite scenario though, with trusted credentials and unique activity ids for the test suite, any LRS failing this is doing something wrong.

**Comment by ljwolford** [comment]
It doesn't look like this test is generating a unique activity id every time so that will need added. Once it starts sending unique ids all the time, I think it's fair to expect the LRS to pass.
