### ISSUE TITLE
Proposed update for checking 'application/json' response header

### ISSUE THREAD

**Issue by TylerDixon** [adlnet/lrs-conformance-test-suite#156]
Referencing an `expect` on a test [here](https://github.com/adlnet/lrs-conformance-test-suite/blob/76e459303fead844e850a6c43d85a37d35e88217/test/v1_0_3/H.Communication2.1-StatementResource.js#L2610), I believe this test may be better suited to use a regular expression to match the `content-type` header, maybe something along the lines of:

`expect(res.headers["content-type"]).to.match(/application\/json/)`

I know of a few frameworks that will automatically format `application/json` responses as `application/json; charset=utf-8`. I think it would still be in spec to do something similar to the above, as well as help accommodate a few different frameworks.

**Comment by bscSCORM** [comment]
@TylerDixon I think you can close this as a duplicate of: https://github.com/adlnet/lrs-conformance-test-suite/issues/137

Which I verified is fixed as of: 653096a

Or leave it open until this hit's `master`, but do be aware the fix is already out there in some branch (I'm a little confused at times as to whether I should be testing against `master` or `development`, I've taken to just seeing if my issue is fixed in either of them)

**Comment by TylerDixon** [comment]
Good catch, thank you!

I think I'll start testing against `development` more from here on out.
