### ISSUE TITLE
PUT without concurrency headers on agent profile expects 204

### ISSUE THREAD

**Issue by TylerDixon** [adlnet/lrs-conformance-test-suite#158]
Test can be found [here](https://github.com/adlnet/lrs-conformance-test-suite/blob/76e459303fead844e850a6c43d85a37d35e88217/test/v1_0_3/H.Communication2.6-AgentProfileResource.js#L48-L52).

This seems to test the opposite of the requirement found [here](https://github.com/adlnet/xAPI-Spec/blob/55432192c559c2a81a4577b5a15d2a212609705c/xAPI-Communication.md#client-requirements):
* A Client making a PUT request to either the Agent Profile Resource or Activity Profile Resource MUST include the "If-Match" header or the If-None-Match header.

This requirement specifies the _client_ as the MUST, but it seems to be interpretable as the LRS should reject in cases of those headers are missing. If this is not the case, then I can move this over to the xAPI-Spec repo issues instead.

**Comment by garemoko** [comment]
We've worked on the principle that the LRS is required to validate all client MUST requirements. 

I can't find a reference for that in the spec itself, but that's the approach we've been taking. The closest I can find in the spec is `The LRS SHOULD enforce rules regarding structure.`

**Comment by bscSCORM** [comment]
I think this is an exception, because the principle that the LRS has to validate a client's `MUST` requirements is a general one, and we have a more specific requirement a little ways down from the one @TylerDixon linked:

> If a PUT request is received without either header for a resource that already exists, the LRS:

This requirement is completely irrelevant if the LRS has to reject requests without either header, and being more specific I think we should read into it the implication that this condition *can* in fact be reached, and that said implication should override the general requirement.

**Comment by bscSCORM** [comment]
There could be enough ambiguity here that the test should allow either `204` _or_ `400`.

**Comment by ljwolford** [comment]
test is wrong, fix to include header
write another test to not include these headers, expect 400 or 409

**Comment by cr8onski** [comment]
fixed in pr #169
