### ISSUE TITLE
Missing test for invalid JSON

### ISSUE THREAD

**Issue by ryansmith94** [adlnet/lrs-conformance-test-suite#223]
Should test that sending non JSON content with a JSON content type header returns a 400.

**Comment by garemoko** [comment]
Relevant spec requirement:

```The LRS SHOULD* reject any request with 400 Bad Request status where the content type header does not match the content included in the request or... ```

So it's a SHOULD*, not a MUST so technically doesn't belong in the conformance test. Still, this seems like an important issue to discuss further given the number of authoring tools that apparently use the wrong context type header.

**Comment by garemoko** [comment]
We still need to answer the question of what LRS vendors should do in this scenario though. The SHOULD* is a strong recommendation, so do we follow it and break compatibility with a bunch of courses? Be good to discuss on the next spec call.

**Comment by ryansmith94** [comment]
Realistically we're just going to have to allow these requests in for now and maybe schedule a point in the future to revisit this issue so that we can correctly return 400s in the future.

**Comment by garemoko** [comment]
@ryansmith94 [also noted](https://github.com/LearningLocker/learninglocker/issues/1022#issuecomment-344568089) that if the LRS does accept the request, a secondary problem is what to do with subsequent GET requests for the document. Should the LRS:

1. Return the document as it was PUT with an application/json content type and invalid json content (This is what Watershed does today). 
2. Return the document as it was PUT but modify the content type header to match the content (i.e. set it to text/plain)
3. Keep the application/json header and modify the content to make it valid json (by enclosing it in quotes). 

Presumably at least option 3 and maybe option 2 would cause problems for applications fetching the data and not expecting the quotes. 

My preference is option 1 since I don't think the LRS should take responsibility for trying to fix the data. If it accepts the data, it should return it in the same format in which it accepts it.

**Comment by ryansmith94** [comment]
I can confirm that Captivate does not expect the quotes, but doesn't care about the content type.

**Comment by ryansmith94** [comment]
I'm which case, I'm in favour of option 2, otherwise option 1 may cause issues later when they address the issue and expect the quotes.

**Comment by ryansmith94** [comment]
Actually I'm not sure, option 1 or 2 are equally find depending on how they fix the issue

**Comment by ryansmith94** [comment]
**Scenario A**
If they fix the issue by wrapping their content in quotes, then in order to support previous state sent in, they will still need to allow the content to be sent back with and without quotes.

**Scenario B**
If they fix the issue by changing the header to text/plain, they can continue to expect the content back without quotes.

**Option 1**
Option 1 is feasible in both scenarios, however, it means that the LRS sends back invalid JSON responses in addition to accepting invalid JSON requests.

**Option 2**
Option 2 is feasible in both scenarios, but doesn't mean that the LRS has to send back invalid JSON responses. Admittedly, it's a bit strange to switch the content type, but since the Scorm Driver doesn't seem to care I don't think it matters.

**Comment by ryansmith94** [comment]
Once this becomes unnecessary, Option 2 is a simple code change to no longer support the invalid requests, whereas Option 1 potentially requires database migrations to wrap the old content in quotes in addition to a code change to no longer support the invalid requests and a code change to stop sending invalid responses.

**Comment by garemoko** [comment]
https://github.com/adlnet/xAPI-Spec/issues/1070#issuecomment-351501226
