### ISSUE TITLE
[2.0.0] Alternate Request Syntax > 401 Unauthorized must be accepted as a legitimate response when authorization header is not provided 

### ISSUE THREAD

**Issue by integralla** [adlnet/lrs-conformance-test-suite#267]
The tests in test/v2_0/H.Communication1.3-AlternateRequestSyntax.js ensure that an LRS will reject a request using the alternate request syntax. All but one of these tests include the "Authorization" header (as a header, not just in the form), meaning that the LRS is able to still authenticate the request before validating the request body. However, there is one test where the "Authorization" header is omitted but still expects a 400 Bad Request response, rather than a 401 Unauthorized response. This is problematic for any LRS that authenticates a request before performing further request validation.

That specific test is titled "will pass PUT with content body which is url encoded".

I would propose that the test accept either a 400 or a 401 response in this scenario because there doesn't appear to be a standard defined for whether the auth headers are checked before the request content, or visa versa. In general, though, I think the former is more common and should certainly be allowed.

**Comment by vbhayden** [comment]
Forgot to get back to you on this, sorry!

I agree, will look at how to allow both responses today -- thanks for relaying this!

**Comment by vbhayden** [comment]
Afternoon @integralla 

The live site was updated today with an updated version of the suite, which should allow any status between 400-499 for the alternate request formats.

Since the IEEE document itself doesn't actually mention Alternate Request Syntax, it might be worth removing that batch from the suite in the future.

Thanks for bringing this up, sorry it took a bit!
